# Generated by Django 5.2.12 on 2026-04-14 18:27

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('phone', models.CharField(blank=True, max_length=20, verbose_name='Телефон')),
                ('student_id', models.CharField(blank=True, max_length=6, verbose_name='Студенческий билет')),
                ('faculty', models.CharField(blank=True, choices=[('fkti', 'ФКТИ'), ('frt', 'ФРТ'), ('fea', 'ФЭА'), ('fibs', 'ФИБС'), ('gf', 'ГФ'), ('inprotech', 'ИНПРОТЕХ')], max_length=20, verbose_name='Факультет')),
                ('course', models.PositiveSmallIntegerField(blank=True, choices=[('b1', '1 курс (бакалавриат/специалитет)'), ('b2', '2 курс (бакалавриат/специалитет)'), ('b3', '3 курс (бакалавриат/специалитет)'), ('b4', '4 курс (бакалавриат/специалитет)'), ('s5', '5 курс (специалитет)'), ('m1', '1 курс (магистратура)'), ('m2', '2 курс (магистратура)'), ('postgrad', 'аспирантура')], null=True, verbose_name='Курс')),
                ('avatar', models.ImageField(blank=True, null=True, upload_to='avatars/', verbose_name='Аватар')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='profile', to=settings.AUTH_USER_MODEL, verbose_name='Пользователь')),
            ],
            options={
                'verbose_name': 'Профиль пользователя',
                'verbose_name_plural': 'Профили пользователей',
            },
        ),
    ]
