# Generated by Django 5.2.12 on 2026-05-17 17:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='course',
            field=models.CharField(blank=True, choices=[('b1', '1 курс (бакалавриат/специалитет)'), ('b2', '2 курс (бакалавриат/специалитет)'), ('b3', '3 курс (бакалавриат/специалитет)'), ('b4', '4 курс (бакалавриат/специалитет)'), ('s5', '5 курс (специалитет)'), ('m1', '1 курс (магистратура)'), ('m2', '2 курс (магистратура)'), ('postgrad', 'аспирантура')], max_length=20, null=True, verbose_name='Курс / Ступень обучения'),
        ),
    ]
