# Generated by Django 5.2.13 on 2026-04-17 09:09

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Space',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='Название')),
                ('slug', models.SlugField(max_length=200, unique=True, verbose_name='URL')),
                ('description', models.TextField(verbose_name='Полное описание')),
                ('short_description', models.CharField(max_length=200, verbose_name='Краткое описание')),
                ('capacity', models.PositiveIntegerField(verbose_name='Вместимость (человек)')),
                ('price_per_hour', models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='Цена за час (₽)')),
                ('image', models.ImageField(blank=True, null=True, upload_to='spaces/', verbose_name='Главное изображение')),
                ('is_available', models.BooleanField(default=True, verbose_name='Доступно для бронирования')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата добавления')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Дата обновления')),
            ],
            options={
                'verbose_name': 'Пространство',
                'verbose_name_plural': 'Пространства',
                'ordering': ['name'],
            },
        ),
    ]
