# Generated by Django 5.2.12 on 2026-05-09 17:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('spaces', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='space',
            name='show_on_homepage',
            field=models.BooleanField(default=False, verbose_name='Показывать на главной странице'),
        ),
    ]
