# Generated by Django 5.2.12 on 2026-05-17 17:18

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookings', '0001_initial'),
        ('spaces', '0002_space_show_on_homepage'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='booking',
            unique_together={('space', 'start_datetime', 'end_datetime')},
        ),
        migrations.AddIndex(
            model_name='booking',
            index=models.Index(fields=['space', 'start_datetime'], name='bookings_bo_space_i_524a02_idx'),
        ),
    ]
